INSERT INTO Country (CountryId, Name) VALUES (154, "Palau");
INSERT INTO Country (CountryId, Name) VALUES (264, "AIR PRINT");
INSERT INTO Country (CountryId, Name) VALUES (74, "Kenya");
INSERT INTO Country (CountryId, Name) VALUES (181, "Aruba");
INSERT INTO Country (CountryId, Name) VALUES (184, "Trinidad and Tobago");
INSERT INTO Country (CountryId, Name) VALUES (246, "Republic of Korea");
INSERT INTO Country (CountryId, Name) VALUES (56, "Malawi");
INSERT INTO Country (CountryId, Name) VALUES (105, "Slovakia");
INSERT INTO Country (CountryId, Name) VALUES (317, "Netherland");
INSERT INTO Country (CountryId, Name) VALUES (262, "AIRFLIGHT");
INSERT INTO Country (CountryId, Name) VALUES (320, "SWISSBIRD");
INSERT INTO Country (CountryId, Name) VALUES (44, "Comoros");
INSERT INTO Country (CountryId, Name) VALUES (286, "AQUILINE");
INSERT INTO Country (CountryId, Name) VALUES (216, "Mongolia");
INSERT INTO Country (CountryId, Name) VALUES (17, "Estonia");
INSERT INTO Country (CountryId, Name) VALUES (318, "ACOM");
INSERT INTO Country (CountryId, Name) VALUES (178, "Virgin Islands");
INSERT INTO Country (CountryId, Name) VALUES (9, "Cote d'Ivoire");
INSERT INTO Country (CountryId, Name) VALUES (277, "ALL STAR");
INSERT INTO Country (CountryId, Name) VALUES (133, "Antarctica");
INSERT INTO Country (CountryId, Name) VALUES (120, "Belize");
INSERT INTO Country (CountryId, Name) VALUES (235,  Fogo Island");
INSERT INTO Country (CountryId, Name) VALUES (301, "Republic of the Congo");
INSERT INTO Country (CountryId, Name) VALUES (18, "Finland");
INSERT INTO Country (CountryId, Name) VALUES (204, "Thailand");
INSERT INTO Country (CountryId, Name) VALUES (255, "Macao");
INSERT INTO Country (CountryId, Name) VALUES (259, "ASTORIA");
INSERT INTO Country (CountryId, Name) VALUES (43, "Zambia");
INSERT INTO Country (CountryId, Name) VALUES (279, "ATLANTIS CANADA");
INSERT INTO Country (CountryId, Name) VALUES (4, "Canada");
INSERT INTO Country (CountryId, Name) VALUES (166, "Suriname");
INSERT INTO Country (CountryId, Name) VALUES (58, "Mali");
INSERT INTO Country (CountryId, Name) VALUES (298, "Russian Federation");
INSERT INTO Country (CountryId, Name) VALUES (112, "Nicaragua");
INSERT INTO Country (CountryId, Name) VALUES (40, "Mauritius");
INSERT INTO Country (CountryId, Name) VALUES (169, "Uruguay");
INSERT INTO Country (CountryId, Name) VALUES (91, "Czech Republic");
INSERT INTO Country (CountryId, Name) VALUES (38, "Equatorial Guinea");
INSERT INTO Country (CountryId, Name) VALUES (39, "Saint Helena");
INSERT INTO Country (CountryId, Name) VALUES (283, "AVIANCA");
INSERT INTO Country (CountryId, Name) VALUES (45, "Mayotte");
INSERT INTO Country (CountryId, Name) VALUES (304, "AIR-MAUR");
INSERT INTO Country (CountryId, Name) VALUES (174, "Dominica");
INSERT INTO Country (CountryId, Name) VALUES (15, "Germany");
INSERT INTO Country (CountryId, Name) VALUES (78, "South Sudan");
INSERT INTO Country (CountryId, Name) VALUES (292, "AIR FREIGHTER");
INSERT INTO Country (CountryId, Name) VALUES (137, "Iran");
INSERT INTO Country (CountryId, Name) VALUES (53, "Seychelles");
INSERT INTO Country (CountryId, Name) VALUES (123, "Tonga");
INSERT INTO Country (CountryId, Name) VALUES (51, "Sao Tome and Principe");
INSERT INTO Country (CountryId, Name) VALUES (69, "Ethiopia");
INSERT INTO Country (CountryId, Name) VALUES (276, "AEROSUN");
INSERT INTO Country (CountryId, Name) VALUES (11, "Niger");
INSERT INTO Country (CountryId, Name) VALUES (278, "AIR CLASS");
INSERT INTO Country (CountryId, Name) VALUES (173, "Barbados");
INSERT INTO Country (CountryId, Name) VALUES (12, "Tunisia");
INSERT INTO Country (CountryId, Name) VALUES (160, "Brazil");
INSERT INTO Country (CountryId, Name) VALUES (118, "Cayman Islands");
INSERT INTO Country (CountryId, Name) VALUES (294, "AIRMAN");
INSERT INTO Country (CountryId, Name) VALUES (79, "Tanzania");
INSERT INTO Country (CountryId, Name) VALUES (64, "Morocco");
INSERT INTO Country (CountryId, Name) VALUES (251, "Canadian Territories");
INSERT INTO Country (CountryId, Name) VALUES (127, "Samoa");
INSERT INTO Country (CountryId, Name) VALUES (109, "Honduras");
INSERT INTO Country (CountryId, Name) VALUES (140, "West Bank");
INSERT INTO Country (CountryId, Name) VALUES (125, "Australia");
INSERT INTO Country (CountryId, Name) VALUES (273, "AIREX");
INSERT INTO Country (CountryId, Name) VALUES (88, "Hungary");
INSERT INTO Country (CountryId, Name) VALUES (52, "Mozambique");
INSERT INTO Country (CountryId, Name) VALUES (226, "Nauru");
INSERT INTO Country (CountryId, Name) VALUES (19, "United Kingdom");
INSERT INTO Country (CountryId, Name) VALUES (308, "DRAGON");
INSERT INTO Country (CountryId, Name) VALUES (97, "Romania");
INSERT INTO Country (CountryId, Name) VALUES (6, "Benin");
INSERT INTO Country (CountryId, Name) VALUES (28, "Luxembourg");
INSERT INTO Country (CountryId, Name) VALUES (249, "AEROCENTER");
INSERT INTO Country (CountryId, Name) VALUES (237, "Western Sahara");
INSERT INTO Country (CountryId, Name) VALUES (214, "China");
INSERT INTO Country (CountryId, Name) VALUES (90, "Slovenia");
INSERT INTO Country (CountryId, Name) VALUES (65, "Senegal");
INSERT INTO Country (CountryId, Name) VALUES (143, "United Arab Emirates");
INSERT INTO Country (CountryId, Name) VALUES (266, "ALASKA PACIFIC");
INSERT INTO Country (CountryId, Name) VALUES (299, "Air S");
INSERT INTO Country (CountryId, Name) VALUES (81, "Albania");
INSERT INTO Country (CountryId, Name) VALUES (293, "RENTAXEL");
INSERT INTO Country (CountryId, Name) VALUES (75, "Libya");
INSERT INTO Country (CountryId, Name) VALUES (150, "Guam");
INSERT INTO Country (CountryId, Name) VALUES (104, "Montenegro");
INSERT INTO Country (CountryId, Name) VALUES (241, "Myanmar");
INSERT INTO Country (CountryId, Name) VALUES (229, "Djibouti");
INSERT INTO Country (CountryId, Name) VALUES (41, "British Indian Ocean Territory");
INSERT INTO Country (CountryId, Name) VALUES (126, "Wallis and Futuna");
INSERT INTO Country (CountryId, Name) VALUES (230, "Montserrat");
INSERT INTO Country (CountryId, Name) VALUES (282, "AUSA");
INSERT INTO Country (CountryId, Name) VALUES (48, "Angola");
INSERT INTO Country (CountryId, Name) VALUES (242, "Svalbard");
INSERT INTO Country (CountryId, Name) VALUES (113, "Panama");
INSERT INTO Country (CountryId, Name) VALUES (16, "United States");
INSERT INTO Country (CountryId, Name) VALUES (199, "Hong Kong");
INSERT INTO Country (CountryId, Name) VALUES (135, "Bahrain");
INSERT INTO Country (CountryId, Name) VALUES (258, "ALCON");
INSERT INTO Country (CountryId, Name) VALUES (49, "Puerto Rico");
INSERT INTO Country (CountryId, Name) VALUES (296, "AZIMUT");
INSERT INTO Country (CountryId, Name) VALUES (29, "Norway");
INSERT INTO Country (CountryId, Name) VALUES (83, "Cyprus");
INSERT INTO Country (CountryId, Name) VALUES (233, "Niue");
INSERT INTO Country (CountryId, Name) VALUES (311, "ALDAWLYH AIR");
INSERT INTO Country (CountryId, Name) VALUES (155, "Taiwan");
INSERT INTO Country (CountryId, Name) VALUES (180, "Saint Lucia");
INSERT INTO Country (CountryId, Name) VALUES (222, "Yemen");
INSERT INTO Country (CountryId, Name) VALUES (272, "ARMSTRONG");
INSERT INTO Country (CountryId, Name) VALUES (260, "COMPANY AS");
INSERT INTO Country (CountryId, Name) VALUES (321, "AEROSOL");
INSERT INTO Country (CountryId, Name) VALUES (215, "Korea");
INSERT INTO Country (CountryId, Name) VALUES (92, "Israel");
INSERT INTO Country (CountryId, Name) VALUES (87, "Saint Pierre and Miquelon");
INSERT INTO Country (CountryId, Name) VALUES (73, "Egypt");
INSERT INTO Country (CountryId, Name) VALUES (128, "American Samoa");
INSERT INTO Country (CountryId, Name) VALUES (47, "Madagascar");
INSERT INTO Country (CountryId, Name) VALUES (102, "Gibraltar");
INSERT INTO Country (CountryId, Name) VALUES (82, "Bulgaria");
INSERT INTO Country (CountryId, Name) VALUES (285, "AVEMEX");
INSERT INTO Country (CountryId, Name) VALUES (114, "Costa Rica");
INSERT INTO Country (CountryId, Name) VALUES (219, "Armenia");
INSERT INTO Country (CountryId, Name) VALUES (205, "Indonesia");
INSERT INTO Country (CountryId, Name) VALUES (213, "Norfolk Island");
INSERT INTO Country (CountryId, Name) VALUES (141, "Kuwait");
INSERT INTO Country (CountryId, Name) VALUES (252, "AEROCESAR");
INSERT INTO Country (CountryId, Name) VALUES (168, "Peru");
INSERT INTO Country (CountryId, Name) VALUES (202, "Nepal");
INSERT INTO Country (CountryId, Name) VALUES (60, "Spain");
INSERT INTO Country (CountryId, Name) VALUES (261, "AIRPAC");
INSERT INTO Country (CountryId, Name) VALUES (8, "Ghana");
INSERT INTO Country (CountryId, Name) VALUES (256, "ANTARES");
INSERT INTO Country (CountryId, Name) VALUES (37, "Central African Republic");
INSERT INTO Country (CountryId, Name) VALUES (139, "Jordan");
INSERT INTO Country (CountryId, Name) VALUES (100, "Moldova");
INSERT INTO Country (CountryId, Name) VALUES (280, "AUDI AIR");
INSERT INTO Country (CountryId, Name) VALUES (98, "Switzerland");
INSERT INTO Country (CountryId, Name) VALUES (245, "");
INSERT INTO Country (CountryId, Name) VALUES (190, "Russia");
INSERT INTO Country (CountryId, Name) VALUES (303, "Syrian Arab Republic");
INSERT INTO Country (CountryId, Name) VALUES (93, "Malta");
INSERT INTO Country (CountryId, Name) VALUES (20, "Guernsey");
INSERT INTO Country (CountryId, Name) VALUES (267, "AEROPERLAS");
INSERT INTO Country (CountryId, Name) VALUES (95, "Portugal");
INSERT INTO Country (CountryId, Name) VALUES (59, "Gambia");
INSERT INTO Country (CountryId, Name) VALUES (208, "Malaysia");
INSERT INTO Country (CountryId, Name) VALUES (89, "Italy");
INSERT INTO Country (CountryId, Name) VALUES (57, "Lesotho");
INSERT INTO Country (CountryId, Name) VALUES (322, "VELES");
INSERT INTO Country (CountryId, Name) VALUES (176, "Guadeloupe");
INSERT INTO Country (CountryId, Name) VALUES (212, "Christmas Island");
INSERT INTO Country (CountryId, Name) VALUES (206, "Vietnam");
INSERT INTO Country (CountryId, Name) VALUES (148, "Qatar");
INSERT INTO Country (CountryId, Name) VALUES (291, "AEROWEE");
INSERT INTO Country (CountryId, Name) VALUES (234,  Niuafo'ou Island");
INSERT INTO Country (CountryId, Name) VALUES (30, "Poland");
INSERT INTO Country (CountryId, Name) VALUES (194, "Uzbekistan");
INSERT INTO Country (CountryId, Name) VALUES (210, "East Timor");
INSERT INTO Country (CountryId, Name) VALUES (247, "Ivory Coast");
INSERT INTO Country (CountryId, Name) VALUES (221, "Palestine");
INSERT INTO Country (CountryId, Name) VALUES (228, "Namibia");
INSERT INTO Country (CountryId, Name) VALUES (270, "AVIOQUINTANA");
INSERT INTO Country (CountryId, Name) VALUES (157, "South Korea");
INSERT INTO Country (CountryId, Name) VALUES (250, "Somali Republic");
INSERT INTO Country (CountryId, Name) VALUES (211, "Singapore");
INSERT INTO Country (CountryId, Name) VALUES (288, "AEROVARADERO");
INSERT INTO Country (CountryId, Name) VALUES (171, "Guyana");
INSERT INTO Country (CountryId, Name) VALUES (124, "Kiribati");
INSERT INTO Country (CountryId, Name) VALUES (309, "UNIFORM OSCAR");
INSERT INTO Country (CountryId, Name) VALUES (21, "Jersey");
INSERT INTO Country (CountryId, Name) VALUES (187, "Kazakhstan");
INSERT INTO Country (CountryId, Name) VALUES (257, "AVINOR");
INSERT INTO Country (CountryId, Name) VALUES (77, "Sudan");
INSERT INTO Country (CountryId, Name) VALUES (71, "Burundi");
INSERT INTO Country (CountryId, Name) VALUES (107, "Dominican Republic");
INSERT INTO Country (CountryId, Name) VALUES (243, "North Korea");
INSERT INTO Country (CountryId, Name) VALUES (72, "Somalia");
INSERT INTO Country (CountryId, Name) VALUES (186, "Saint Vincent and the Grenadines");
INSERT INTO Country (CountryId, Name) VALUES (159, "Turkmenistan");
INSERT INTO Country (CountryId, Name) VALUES (10, "Nigeria");
INSERT INTO Country (CountryId, Name) VALUES (201, "Macau");
INSERT INTO Country (CountryId, Name) VALUES (50, "Gabon");
INSERT INTO Country (CountryId, Name) VALUES (23, "Falkland Islands");
INSERT INTO Country (CountryId, Name) VALUES (151, "Marshall Islands");
INSERT INTO Country (CountryId, Name) VALUES (68, "Cape Verde");
INSERT INTO Country (CountryId, Name) VALUES (119, "Bahamas");
INSERT INTO Country (CountryId, Name) VALUES (84, "Croatia");
INSERT INTO Country (CountryId, Name) VALUES (209, "Brunei");
INSERT INTO Country (CountryId, Name) VALUES (248, "Democratic Republic of the Congo");
INSERT INTO Country (CountryId, Name) VALUES (111, "Mexico");
INSERT INTO Country (CountryId, Name) VALUES (319, " Boonville Stage Line");
INSERT INTO Country (CountryId, Name) VALUES (70, "Maldives");
INSERT INTO Country (CountryId, Name) VALUES (316, "UNited Kingdom");
INSERT INTO Country (CountryId, Name) VALUES (185, "British Virgin Islands");
INSERT INTO Country (CountryId, Name) VALUES (265, "APPALACHIAN");
INSERT INTO Country (CountryId, Name) VALUES (7, "Burkina Faso");
INSERT INTO Country (CountryId, Name) VALUES (239, "Cocos (Keeling) Islands");
INSERT INTO Country (CountryId, Name) VALUES (244, "Wake Island");
INSERT INTO Country (CountryId, Name) VALUES (138, "Argentina");
INSERT INTO Country (CountryId, Name) VALUES (27, "Faroe Islands");
INSERT INTO Country (CountryId, Name) VALUES (121, "Cook Islands");
INSERT INTO Country (CountryId, Name) VALUES (177, "Grenada");
INSERT INTO Country (CountryId, Name) VALUES (179, "Saint Kitts and Nevis");
INSERT INTO Country (CountryId, Name) VALUES (182, "Netherlands Antilles");
INSERT INTO Country (CountryId, Name) VALUES (231, "Monaco");
INSERT INTO Country (CountryId, Name) VALUES (170, "Venezuela");
INSERT INTO Country (CountryId, Name) VALUES (106, "Turks and Caicos Islands");
INSERT INTO Country (CountryId, Name) VALUES (302, "S");
INSERT INTO Country (CountryId, Name) VALUES (207, "Burma");
INSERT INTO Country (CountryId, Name) VALUES (200, "Laos");
INSERT INTO Country (CountryId, Name) VALUES (26, "Denmark");
INSERT INTO Country (CountryId, Name) VALUES (193, "Tajikistan");
INSERT INTO Country (CountryId, Name) VALUES (85, "Greece");
INSERT INTO Country (CountryId, Name) VALUES (195, "India");
INSERT INTO Country (CountryId, Name) VALUES (271, " S.A.");
INSERT INTO Country (CountryId, Name) VALUES (217, "Latvia");
INSERT INTO Country (CountryId, Name) VALUES (101, "Macedonia");
INSERT INTO Country (CountryId, Name) VALUES (163, "Paraguay");
INSERT INTO Country (CountryId, Name) VALUES (110, "Jamaica");
INSERT INTO Country (CountryId, Name) VALUES (158, "Philippines");
INSERT INTO Country (CountryId, Name) VALUES (34, "Congo (Brazzaville)");
INSERT INTO Country (CountryId, Name) VALUES (306, "Democratic Republic of Congo");
INSERT INTO Country (CountryId, Name) VALUES (130, "Vanuatu");
INSERT INTO Country (CountryId, Name) VALUES (218, "Lithuania");
INSERT INTO Country (CountryId, Name) VALUES (167, "French Guiana");
INSERT INTO Country (CountryId, Name) VALUES (94, "Austria");
INSERT INTO Country (CountryId, Name) VALUES (232, "Johnston Atoll");
INSERT INTO Country (CountryId, Name) VALUES (55, "Zimbabwe");
INSERT INTO Country (CountryId, Name) VALUES (191, "Ukraine");
INSERT INTO Country (CountryId, Name) VALUES (63, "Liberia");
INSERT INTO Country (CountryId, Name) VALUES (253, "AIRPORT HELICOPTER");
INSERT INTO Country (CountryId, Name) VALUES (223, "Georgia");
INSERT INTO Country (CountryId, Name) VALUES (132, "New Zealand");
INSERT INTO Country (CountryId, Name) VALUES (269, "ATCO");
INSERT INTO Country (CountryId, Name) VALUES (238,  Sheffield");
INSERT INTO Country (CountryId, Name) VALUES (62, "Guinea-Bissau");
INSERT INTO Country (CountryId, Name) VALUES (46, "Reunion");
INSERT INTO Country (CountryId, Name) VALUES (203, "Bhutan");
INSERT INTO Country (CountryId, Name) VALUES (313, "LAP");
INSERT INTO Country (CountryId, Name) VALUES (142, "Lebanon");
INSERT INTO Country (CountryId, Name) VALUES (287, "ACTIVE AERO");
INSERT INTO Country (CountryId, Name) VALUES (144, "Oman");
INSERT INTO Country (CountryId, Name) VALUES (136, "Saudi Arabia");
INSERT INTO Country (CountryId, Name) VALUES (300, "Democratic People's Republic of Korea");
INSERT INTO Country (CountryId, Name) VALUES (188, "Kyrgyzstan");
INSERT INTO Country (CountryId, Name) VALUES (108, "Guatemala");
INSERT INTO Country (CountryId, Name) VALUES (268, "AEROPUMA");
INSERT INTO Country (CountryId, Name) VALUES (175, "Martinique");
INSERT INTO Country (CountryId, Name) VALUES (61, "Sierra Leone");
INSERT INTO Country (CountryId, Name) VALUES (122, "Fiji");
INSERT INTO Country (CountryId, Name) VALUES (33, "Botswana");
INSERT INTO Country (CountryId, Name) VALUES (76, "Rwanda");
INSERT INTO Country (CountryId, Name) VALUES (117, "Cuba");
INSERT INTO Country (CountryId, Name) VALUES (147, "Syria");
INSERT INTO Country (CountryId, Name) VALUES (116, "Haiti");
INSERT INTO Country (CountryId, Name) VALUES (145, "Pakistan");
INSERT INTO Country (CountryId, Name) VALUES (152, "Midway Islands");
INSERT INTO Country (CountryId, Name) VALUES (281, "AURORA AIR");
INSERT INTO Country (CountryId, Name) VALUES (165, "Bolivia");
INSERT INTO Country (CountryId, Name) VALUES (31, "Sweden");
INSERT INTO Country (CountryId, Name) VALUES (164, "Colombia");
INSERT INTO Country (CountryId, Name) VALUES (192, "Belarus");
INSERT INTO Country (CountryId, Name) VALUES (312, "ODINN");
INSERT INTO Country (CountryId, Name) VALUES (307, "ASUR");
INSERT INTO Country (CountryId, Name) VALUES (96, "Bosnia and Herzegovina");
INSERT INTO Country (CountryId, Name) VALUES (161, "Chile");
INSERT INTO Country (CountryId, Name) VALUES (86, "France");
INSERT INTO Country (CountryId, Name) VALUES (131, "New Caledonia");
INSERT INTO Country (CountryId, Name) VALUES (297, "ARIZAIR");
INSERT INTO Country (CountryId, Name) VALUES (224, "Bermuda");
INSERT INTO Country (CountryId, Name) VALUES (289, "AIRNAT");
INSERT INTO Country (CountryId, Name) VALUES (32, "South Africa");
INSERT INTO Country (CountryId, Name) VALUES (42, "Cameroon");
INSERT INTO Country (CountryId, Name) VALUES (183, "Anguilla");
INSERT INTO Country (CountryId, Name) VALUES (314, "Lao Peoples Democratic Republic");
INSERT INTO Country (CountryId, Name) VALUES (315, "WATCHDOG");
INSERT INTO Country (CountryId, Name) VALUES (220, "Eritrea");
INSERT INTO Country (CountryId, Name) VALUES (22, "Isle of Man");
INSERT INTO Country (CountryId, Name) VALUES (54, "Chad");
INSERT INTO Country (CountryId, Name) VALUES (156, "Japan");
INSERT INTO Country (CountryId, Name) VALUES (5, "Algeria");
INSERT INTO Country (CountryId, Name) VALUES (1, "Papua New Guinea");
INSERT INTO Country (CountryId, Name) VALUES (13, "Togo");
INSERT INTO Country (CountryId, Name) VALUES (290, "AIRWAVE");
INSERT INTO Country (CountryId, Name) VALUES (24, "Netherlands");
INSERT INTO Country (CountryId, Name) VALUES (66, "Mauritania");
INSERT INTO Country (CountryId, Name) VALUES (36, "Swaziland");
INSERT INTO Country (CountryId, Name) VALUES (284, "ALAMO");
INSERT INTO Country (CountryId, Name) VALUES (99, "Turkey");
INSERT INTO Country (CountryId, Name) VALUES (225, "Solomon Islands");
INSERT INTO Country (CountryId, Name) VALUES (67, "Guinea");
INSERT INTO Country (CountryId, Name) VALUES (149, "Northern Mariana Islands");
INSERT INTO Country (CountryId, Name) VALUES (275, "SCHEFF");
INSERT INTO Country (CountryId, Name) VALUES (134, "Afghanistan");
INSERT INTO Country (CountryId, Name) VALUES (197, "Cambodia");
INSERT INTO Country (CountryId, Name) VALUES (305, "Hong Kong SAR of China");
INSERT INTO Country (CountryId, Name) VALUES (295, "ATLANTIC NICARAGUA");
INSERT INTO Country (CountryId, Name) VALUES (25, "Ireland");
INSERT INTO Country (CountryId, Name) VALUES (172, "Antigua and Barbuda");
INSERT INTO Country (CountryId, Name) VALUES (263, "ASA PESADA");
INSERT INTO Country (CountryId, Name) VALUES (14, "Belgium");
INSERT INTO Country (CountryId, Name) VALUES (196, "Sri Lanka");
INSERT INTO Country (CountryId, Name) VALUES (103, "Serbia");
INSERT INTO Country (CountryId, Name) VALUES (323, \N);
INSERT INTO Country (CountryId, Name) VALUES (240, "South Georgia and the Islands");
INSERT INTO Country (CountryId, Name) VALUES (274, "ALASKA");
INSERT INTO Country (CountryId, Name) VALUES (129, "French Polynesia");
INSERT INTO Country (CountryId, Name) VALUES (115, "El Salvador");
INSERT INTO Country (CountryId, Name) VALUES (310, "Russia]]");
INSERT INTO Country (CountryId, Name) VALUES (146, "Iraq");
INSERT INTO Country (CountryId, Name) VALUES (162, "Ecuador");
INSERT INTO Country (CountryId, Name) VALUES (236,  Santiago Island");
INSERT INTO Country (CountryId, Name) VALUES (227, "Tuvalu");
INSERT INTO Country (CountryId, Name) VALUES (3, "Iceland");
INSERT INTO Country (CountryId, Name) VALUES (80, "Uganda");
INSERT INTO Country (CountryId, Name) VALUES (254, "ALNACIONAL");
INSERT INTO Country (CountryId, Name) VALUES (153, "Micronesia");
INSERT INTO Country (CountryId, Name) VALUES (2, "Greenland");
INSERT INTO Country (CountryId, Name) VALUES (35, "Congo (Kinshasa)");
INSERT INTO Country (CountryId, Name) VALUES (198, "Bangladesh");
INSERT INTO Country (CountryId, Name) VALUES (189, "Azerbaijan");
