INSERT INTO Country (CountryId, CountryName) VALUES (170, 'Venezuela');
INSERT INTO Country (CountryId, CountryName) VALUES (187, 'Kazakhstan');
INSERT INTO Country (CountryId, CountryName) VALUES (302, 'ASUR');
INSERT INTO Country (CountryId, CountryName) VALUES (68, 'Cape Verde');
INSERT INTO Country (CountryId, CountryName) VALUES (274, 'ATLANTIS CANADA');
INSERT INTO Country (CountryId, CountryName) VALUES (104, 'Montenegro');
INSERT INTO Country (CountryId, CountryName) VALUES (252, 'AVINOR');
INSERT INTO Country (CountryId, CountryName) VALUES (29, 'Norway');
INSERT INTO Country (CountryId, CountryName) VALUES (237, 'Myanmar');
INSERT INTO Country (CountryId, CountryName) VALUES (65, 'Senegal');
INSERT INTO Country (CountryId, CountryName) VALUES (241, 'Republic of Korea');
INSERT INTO Country (CountryId, CountryName) VALUES (21, 'Jersey');
INSERT INTO Country (CountryId, CountryName) VALUES (206, 'Vietnam');
INSERT INTO Country (CountryId, CountryName) VALUES (12, 'Tunisia');
INSERT INTO Country (CountryId, CountryName) VALUES (149, 'Northern Mariana Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (276, 'AURORA AIR');
INSERT INTO Country (CountryId, CountryName) VALUES (244, 'AEROCENTER');
INSERT INTO Country (CountryId, CountryName) VALUES (137, 'Iran');
INSERT INTO Country (CountryId, CountryName) VALUES (251, 'ANTARES');
INSERT INTO Country (CountryId, CountryName) VALUES (298, 'Syrian Arab Republic');
INSERT INTO Country (CountryId, CountryName) VALUES (268, 'AIREX');
INSERT INTO Country (CountryId, CountryName) VALUES (98, 'Switzerland');
INSERT INTO Country (CountryId, CountryName) VALUES (263, 'AEROPUMA');
INSERT INTO Country (CountryId, CountryName) VALUES (156, 'Japan');
INSERT INTO Country (CountryId, CountryName) VALUES (87, 'Saint Pierre and Miquelon');
INSERT INTO Country (CountryId, CountryName) VALUES (234, 'Western Sahara');
INSERT INTO Country (CountryId, CountryName) VALUES (176, 'Guadeloupe');
INSERT INTO Country (CountryId, CountryName) VALUES (255, 'COMPANY AS');
INSERT INTO Country (CountryId, CountryName) VALUES (61, 'Sierra Leone');
INSERT INTO Country (CountryId, CountryName) VALUES (281, 'AQUILINE');
INSERT INTO Country (CountryId, CountryName) VALUES (142, 'Lebanon');
INSERT INTO Country (CountryId, CountryName) VALUES (300, 'Hong Kong SAR of China');
INSERT INTO Country (CountryId, CountryName) VALUES (197, 'Cambodia');
INSERT INTO Country (CountryId, CountryName) VALUES (235, 'Cocos (Keeling) Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (294, 'Air S');
INSERT INTO Country (CountryId, CountryName) VALUES (4, 'Canada');
INSERT INTO Country (CountryId, CountryName) VALUES (70, 'Maldives');
INSERT INTO Country (CountryId, CountryName) VALUES (36, 'Swaziland');
INSERT INTO Country (CountryId, CountryName) VALUES (40, 'Mauritius');
INSERT INTO Country (CountryId, CountryName) VALUES (1, 'Papua New Guinea');
INSERT INTO Country (CountryId, CountryName) VALUES (92, 'Israel');
INSERT INTO Country (CountryId, CountryName) VALUES (227, 'Tuvalu');
INSERT INTO Country (CountryId, CountryName) VALUES (121, 'Cook Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (191, 'Ukraine');
INSERT INTO Country (CountryId, CountryName) VALUES (293, 'Russian Federation');
INSERT INTO Country (CountryId, CountryName) VALUES (150, 'Guam');
INSERT INTO Country (CountryId, CountryName) VALUES (230, 'Montserrat');
INSERT INTO Country (CountryId, CountryName) VALUES (305, 'Russia]]');
INSERT INTO Country (CountryId, CountryName) VALUES (72, 'Somalia');
INSERT INTO Country (CountryId, CountryName) VALUES (280, 'AVEMEX');
INSERT INTO Country (CountryId, CountryName) VALUES (136, 'Saudi Arabia');
INSERT INTO Country (CountryId, CountryName) VALUES (80, 'Uganda');
INSERT INTO Country (CountryId, CountryName) VALUES (249, 'ALNACIONAL');
INSERT INTO Country (CountryId, CountryName) VALUES (107, 'Dominican Republic');
INSERT INTO Country (CountryId, CountryName) VALUES (112, 'Nicaragua');
INSERT INTO Country (CountryId, CountryName) VALUES (116, 'Haiti');
INSERT INTO Country (CountryId, CountryName) VALUES (41, 'British Indian Ocean Territory');
INSERT INTO Country (CountryId, CountryName) VALUES (286, 'AEROWEE');
INSERT INTO Country (CountryId, CountryName) VALUES (171, 'Guyana');
INSERT INTO Country (CountryId, CountryName) VALUES (190, 'Russia');
INSERT INTO Country (CountryId, CountryName) VALUES (100, 'Moldova');
INSERT INTO Country (CountryId, CountryName) VALUES (317, 'VELES');
INSERT INTO Country (CountryId, CountryName) VALUES (306, 'ALDAWLYH AIR');
INSERT INTO Country (CountryId, CountryName) VALUES (60, 'Spain');
INSERT INTO Country (CountryId, CountryName) VALUES (198, 'Bangladesh');
INSERT INTO Country (CountryId, CountryName) VALUES (228, 'Namibia');
INSERT INTO Country (CountryId, CountryName) VALUES (208, 'Malaysia');
INSERT INTO Country (CountryId, CountryName) VALUES (223, 'Georgia');
INSERT INTO Country (CountryId, CountryName) VALUES (231, 'Monaco');
INSERT INTO Country (CountryId, CountryName) VALUES (81, 'Albania');
INSERT INTO Country (CountryId, CountryName) VALUES (262, 'AEROPERLAS');
INSERT INTO Country (CountryId, CountryName) VALUES (73, 'Egypt');
INSERT INTO Country (CountryId, CountryName) VALUES (146, 'Iraq');
INSERT INTO Country (CountryId, CountryName) VALUES (101, 'Macedonia');
INSERT INTO Country (CountryId, CountryName) VALUES (157, 'South Korea');
INSERT INTO Country (CountryId, CountryName) VALUES (119, 'Bahamas');
INSERT INTO Country (CountryId, CountryName) VALUES (296, 'Republic of the Congo');
INSERT INTO Country (CountryId, CountryName) VALUES (133, 'Antarctica');
INSERT INTO Country (CountryId, CountryName) VALUES (27, 'Faroe Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (173, 'Barbados');
INSERT INTO Country (CountryId, CountryName) VALUES (134, 'Afghanistan');
INSERT INTO Country (CountryId, CountryName) VALUES (162, 'Ecuador');
INSERT INTO Country (CountryId, CountryName) VALUES (66, 'Mauritania');
INSERT INTO Country (CountryId, CountryName) VALUES (75, 'Libya');
INSERT INTO Country (CountryId, CountryName) VALUES (224, 'Bermuda');
INSERT INTO Country (CountryId, CountryName) VALUES (261, 'ALASKA PACIFIC');
INSERT INTO Country (CountryId, CountryName) VALUES (163, 'Paraguay');
INSERT INTO Country (CountryId, CountryName) VALUES (229, 'Djibouti');
INSERT INTO Country (CountryId, CountryName) VALUES (179, 'Saint Kitts and Nevis');
INSERT INTO Country (CountryId, CountryName) VALUES (284, 'AIRNAT');
INSERT INTO Country (CountryId, CountryName) VALUES (25, 'Ireland');
INSERT INTO Country (CountryId, CountryName) VALUES (200, 'Laos');
INSERT INTO Country (CountryId, CountryName) VALUES (8, 'Ghana');
INSERT INTO Country (CountryId, CountryName) VALUES (158, 'Philippines');
INSERT INTO Country (CountryId, CountryName) VALUES (56, 'Malawi');
INSERT INTO Country (CountryId, CountryName) VALUES (145, 'Pakistan');
INSERT INTO Country (CountryId, CountryName) VALUES (271, 'AEROSUN');
INSERT INTO Country (CountryId, CountryName) VALUES (130, 'Vanuatu');
INSERT INTO Country (CountryId, CountryName) VALUES (275, 'AUDI AIR');
INSERT INTO Country (CountryId, CountryName) VALUES (159, 'Turkmenistan');
INSERT INTO Country (CountryId, CountryName) VALUES (9, 'Cote d''Ivoire');
INSERT INTO Country (CountryId, CountryName) VALUES (5, 'Algeria');
INSERT INTO Country (CountryId, CountryName) VALUES (226, 'Nauru');
INSERT INTO Country (CountryId, CountryName) VALUES (42, 'Cameroon');
INSERT INTO Country (CountryId, CountryName) VALUES (254, 'ASTORIA');
INSERT INTO Country (CountryId, CountryName) VALUES (84, 'Croatia');
INSERT INTO Country (CountryId, CountryName) VALUES (51, 'Sao Tome and Principe');
INSERT INTO Country (CountryId, CountryName) VALUES (35, 'Congo (Kinshasa)');
INSERT INTO Country (CountryId, CountryName) VALUES (54, 'Chad');
INSERT INTO Country (CountryId, CountryName) VALUES (115, 'El Salvador');
INSERT INTO Country (CountryId, CountryName) VALUES (309, 'Lao Peoples Democratic Republic');
INSERT INTO Country (CountryId, CountryName) VALUES (213, 'Norfolk Island');
INSERT INTO Country (CountryId, CountryName) VALUES (205, 'Indonesia');
INSERT INTO Country (CountryId, CountryName) VALUES (181, 'Aruba');
INSERT INTO Country (CountryId, CountryName) VALUES (282, 'ACTIVE AERO');
INSERT INTO Country (CountryId, CountryName) VALUES (169, 'Uruguay');
INSERT INTO Country (CountryId, CountryName) VALUES (28, 'Luxembourg');
INSERT INTO Country (CountryId, CountryName) VALUES (128, 'American Samoa');
INSERT INTO Country (CountryId, CountryName) VALUES (256, 'AIRPAC');
INSERT INTO Country (CountryId, CountryName) VALUES (53, 'Seychelles');
INSERT INTO Country (CountryId, CountryName) VALUES (135, 'Bahrain');
INSERT INTO Country (CountryId, CountryName) VALUES (126, 'Wallis and Futuna');
INSERT INTO Country (CountryId, CountryName) VALUES (199, 'Hong Kong');
INSERT INTO Country (CountryId, CountryName) VALUES (83, 'Cyprus');
INSERT INTO Country (CountryId, CountryName) VALUES (94, 'Austria');
INSERT INTO Country (CountryId, CountryName) VALUES (194, 'Uzbekistan');
INSERT INTO Country (CountryId, CountryName) VALUES (160, 'Brazil');
INSERT INTO Country (CountryId, CountryName) VALUES (97, 'Romania');
INSERT INTO Country (CountryId, CountryName) VALUES (13, 'Togo');
INSERT INTO Country (CountryId, CountryName) VALUES (58, 'Mali');
INSERT INTO Country (CountryId, CountryName) VALUES (17, 'Estonia');
INSERT INTO Country (CountryId, CountryName) VALUES (222, 'Yemen');
INSERT INTO Country (CountryId, CountryName) VALUES (250, 'Macao');
INSERT INTO Country (CountryId, CountryName) VALUES (20, 'Guernsey');
INSERT INTO Country (CountryId, CountryName) VALUES (143, 'United Arab Emirates');
INSERT INTO Country (CountryId, CountryName) VALUES (299, 'AIR-MAUR');
INSERT INTO Country (CountryId, CountryName) VALUES (243, 'Democratic Republic of the Congo');
INSERT INTO Country (CountryId, CountryName) VALUES (279, 'ALAMO');
INSERT INTO Country (CountryId, CountryName) VALUES (118, 'Cayman Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (63, 'Liberia');
INSERT INTO Country (CountryId, CountryName) VALUES (15, 'Germany');
INSERT INTO Country (CountryId, CountryName) VALUES (6, 'Benin');
INSERT INTO Country (CountryId, CountryName) VALUES (313, 'ACOM');
INSERT INTO Country (CountryId, CountryName) VALUES (174, 'Dominica');
INSERT INTO Country (CountryId, CountryName) VALUES (69, 'Ethiopia');
INSERT INTO Country (CountryId, CountryName) VALUES (147, 'Syria');
INSERT INTO Country (CountryId, CountryName) VALUES (203, 'Bhutan');
INSERT INTO Country (CountryId, CountryName) VALUES (168, 'Peru');
INSERT INTO Country (CountryId, CountryName) VALUES (310, 'WATCHDOG');
INSERT INTO Country (CountryId, CountryName) VALUES (253, 'ALCON');
INSERT INTO Country (CountryId, CountryName) VALUES (178, 'Virgin Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (304, 'UNIFORM OSCAR');
INSERT INTO Country (CountryId, CountryName) VALUES (267, 'ARMSTRONG');
INSERT INTO Country (CountryId, CountryName) VALUES (0, 'UNKNOWN');
INSERT INTO Country (CountryId, CountryName) VALUES (10, 'Nigeria');
INSERT INTO Country (CountryId, CountryName) VALUES (71, 'Burundi');
INSERT INTO Country (CountryId, CountryName) VALUES (195, 'India');
INSERT INTO Country (CountryId, CountryName) VALUES (270, 'SCHEFF');
INSERT INTO Country (CountryId, CountryName) VALUES (7, 'Burkina Faso');
INSERT INTO Country (CountryId, CountryName) VALUES (26, 'Denmark');
INSERT INTO Country (CountryId, CountryName) VALUES (79, 'Tanzania');
INSERT INTO Country (CountryId, CountryName) VALUES (295, 'Democratic People''s Republic of Korea');
INSERT INTO Country (CountryId, CountryName) VALUES (59, 'Gambia');
INSERT INTO Country (CountryId, CountryName) VALUES (211, 'Singapore');
INSERT INTO Country (CountryId, CountryName) VALUES (90, 'Slovenia');
INSERT INTO Country (CountryId, CountryName) VALUES (204, 'Thailand');
INSERT INTO Country (CountryId, CountryName) VALUES (82, 'Bulgaria');
INSERT INTO Country (CountryId, CountryName) VALUES (177, 'Grenada');
INSERT INTO Country (CountryId, CountryName) VALUES (16, 'United States');
INSERT INTO Country (CountryId, CountryName) VALUES (120, 'Belize');
INSERT INTO Country (CountryId, CountryName) VALUES (192, 'Belarus');
INSERT INTO Country (CountryId, CountryName) VALUES (264, 'ATCO');
INSERT INTO Country (CountryId, CountryName) VALUES (233, 'Niue');
INSERT INTO Country (CountryId, CountryName) VALUES (64, 'Morocco');
INSERT INTO Country (CountryId, CountryName) VALUES (44, 'Comoros');
INSERT INTO Country (CountryId, CountryName) VALUES (172, 'Antigua and Barbuda');
INSERT INTO Country (CountryId, CountryName) VALUES (23, 'Falkland Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (18, 'Finland');
INSERT INTO Country (CountryId, CountryName) VALUES (232, 'Johnston Atoll');
INSERT INTO Country (CountryId, CountryName) VALUES (48, 'Angola');
INSERT INTO Country (CountryId, CountryName) VALUES (292, 'ARIZAIR');
INSERT INTO Country (CountryId, CountryName) VALUES (125, 'Australia');
INSERT INTO Country (CountryId, CountryName) VALUES (311, 'UNited Kingdom');
INSERT INTO Country (CountryId, CountryName) VALUES (105, 'Slovakia');
INSERT INTO Country (CountryId, CountryName) VALUES (184, 'Trinidad and Tobago');
INSERT INTO Country (CountryId, CountryName) VALUES (103, 'Serbia');
INSERT INTO Country (CountryId, CountryName) VALUES (88, 'Hungary');
INSERT INTO Country (CountryId, CountryName) VALUES (91, 'Czech Republic');
INSERT INTO Country (CountryId, CountryName) VALUES (122, 'Fiji');
INSERT INTO Country (CountryId, CountryName) VALUES (216, 'Mongolia');
INSERT INTO Country (CountryId, CountryName) VALUES (182, 'Netherlands Antilles');
INSERT INTO Country (CountryId, CountryName) VALUES (167, 'French Guiana');
INSERT INTO Country (CountryId, CountryName) VALUES (290, 'ATLANTIC NICARAGUA');
INSERT INTO Country (CountryId, CountryName) VALUES (239, 'North Korea');
INSERT INTO Country (CountryId, CountryName) VALUES (287, 'AIR FREIGHTER');
INSERT INTO Country (CountryId, CountryName) VALUES (214, 'China');
INSERT INTO Country (CountryId, CountryName) VALUES (95, 'Portugal');
INSERT INTO Country (CountryId, CountryName) VALUES (11, 'Niger');
INSERT INTO Country (CountryId, CountryName) VALUES (113, 'Panama');
INSERT INTO Country (CountryId, CountryName) VALUES (86, 'France');
INSERT INTO Country (CountryId, CountryName) VALUES (114, 'Costa Rica');
INSERT INTO Country (CountryId, CountryName) VALUES (269, 'ALASKA');
INSERT INTO Country (CountryId, CountryName) VALUES (31, 'Sweden');
INSERT INTO Country (CountryId, CountryName) VALUES (185, 'British Virgin Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (45, 'Mayotte');
INSERT INTO Country (CountryId, CountryName) VALUES (188, 'Kyrgyzstan');
INSERT INTO Country (CountryId, CountryName) VALUES (297, 'S');
INSERT INTO Country (CountryId, CountryName) VALUES (67, 'Guinea');
INSERT INTO Country (CountryId, CountryName) VALUES (37, 'Central African Republic');
INSERT INTO Country (CountryId, CountryName) VALUES (19, 'United Kingdom');
INSERT INTO Country (CountryId, CountryName) VALUES (277, 'AUSA');
INSERT INTO Country (CountryId, CountryName) VALUES (117, 'Cuba');
INSERT INTO Country (CountryId, CountryName) VALUES (189, 'Azerbaijan');
INSERT INTO Country (CountryId, CountryName) VALUES (308, 'LAP');
INSERT INTO Country (CountryId, CountryName) VALUES (110, 'Jamaica');
INSERT INTO Country (CountryId, CountryName) VALUES (161, 'Chile');
INSERT INTO Country (CountryId, CountryName) VALUES (212, 'Christmas Island');
INSERT INTO Country (CountryId, CountryName) VALUES (34, 'Congo (Brazzaville)');
INSERT INTO Country (CountryId, CountryName) VALUES (89, 'Italy');
INSERT INTO Country (CountryId, CountryName) VALUES (39, 'Saint Helena');
INSERT INTO Country (CountryId, CountryName) VALUES (314, 'Boonville Stage Line');
INSERT INTO Country (CountryId, CountryName) VALUES (57, 'Lesotho');
INSERT INTO Country (CountryId, CountryName) VALUES (55, 'Zimbabwe');
INSERT INTO Country (CountryId, CountryName) VALUES (315, 'SWISSBIRD');
INSERT INTO Country (CountryId, CountryName) VALUES (193, 'Tajikistan');
INSERT INTO Country (CountryId, CountryName) VALUES (219, 'Armenia');
INSERT INTO Country (CountryId, CountryName) VALUES (303, 'DRAGON');
INSERT INTO Country (CountryId, CountryName) VALUES (196, 'Sri Lanka');
INSERT INTO Country (CountryId, CountryName) VALUES (301, 'Democratic Republic of Congo');
INSERT INTO Country (CountryId, CountryName) VALUES (248, 'AIRPORT HELICOPTER');
INSERT INTO Country (CountryId, CountryName) VALUES (218, 'Lithuania');
INSERT INTO Country (CountryId, CountryName) VALUES (186, 'Saint Vincent and the Grenadines');
INSERT INTO Country (CountryId, CountryName) VALUES (85, 'Greece');
INSERT INTO Country (CountryId, CountryName) VALUES (175, 'Martinique');
INSERT INTO Country (CountryId, CountryName) VALUES (245, 'Somali Republic');
INSERT INTO Country (CountryId, CountryName) VALUES (207, 'Burma');
INSERT INTO Country (CountryId, CountryName) VALUES (240, 'Wake Island');
INSERT INTO Country (CountryId, CountryName) VALUES (129, 'French Polynesia');
INSERT INTO Country (CountryId, CountryName) VALUES (220, 'Eritrea');
INSERT INTO Country (CountryId, CountryName) VALUES (33, 'Botswana');
INSERT INTO Country (CountryId, CountryName) VALUES (260, 'APPALACHIAN');
INSERT INTO Country (CountryId, CountryName) VALUES (225, 'Solomon Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (258, 'ASA PESADA');
INSERT INTO Country (CountryId, CountryName) VALUES (257, 'AIRFLIGHT');
INSERT INTO Country (CountryId, CountryName) VALUES (164, 'Colombia');
INSERT INTO Country (CountryId, CountryName) VALUES (99, 'Turkey');
INSERT INTO Country (CountryId, CountryName) VALUES (183, 'Anguilla');
INSERT INTO Country (CountryId, CountryName) VALUES (96, 'Bosnia and Herzegovina');
INSERT INTO Country (CountryId, CountryName) VALUES (24, 'Netherlands');
INSERT INTO Country (CountryId, CountryName) VALUES (259, 'AIR PRINT');
INSERT INTO Country (CountryId, CountryName) VALUES (49, 'Puerto Rico');
INSERT INTO Country (CountryId, CountryName) VALUES (111, 'Mexico');
INSERT INTO Country (CountryId, CountryName) VALUES (221, 'Palestine');
INSERT INTO Country (CountryId, CountryName) VALUES (138, 'Argentina');
INSERT INTO Country (CountryId, CountryName) VALUES (46, 'Reunion');
INSERT INTO Country (CountryId, CountryName) VALUES (132, 'New Zealand');
INSERT INTO Country (CountryId, CountryName) VALUES (78, 'South Sudan');
INSERT INTO Country (CountryId, CountryName) VALUES (238, 'Svalbard');
INSERT INTO Country (CountryId, CountryName) VALUES (30, 'Poland');
INSERT INTO Country (CountryId, CountryName) VALUES (273, 'AIR CLASS');
INSERT INTO Country (CountryId, CountryName) VALUES (312, 'Netherland');
INSERT INTO Country (CountryId, CountryName) VALUES (2, 'Greenland');
INSERT INTO Country (CountryId, CountryName) VALUES (141, 'Kuwait');
INSERT INTO Country (CountryId, CountryName) VALUES (43, 'Zambia');
INSERT INTO Country (CountryId, CountryName) VALUES (289, 'AIRMAN');
INSERT INTO Country (CountryId, CountryName) VALUES (74, 'Kenya');
INSERT INTO Country (CountryId, CountryName) VALUES (50, 'Gabon');
INSERT INTO Country (CountryId, CountryName) VALUES (148, 'Qatar');
INSERT INTO Country (CountryId, CountryName) VALUES (153, 'Micronesia');
INSERT INTO Country (CountryId, CountryName) VALUES (154, 'Palau');
INSERT INTO Country (CountryId, CountryName) VALUES (139, 'Jordan');
INSERT INTO Country (CountryId, CountryName) VALUES (127, 'Samoa');
INSERT INTO Country (CountryId, CountryName) VALUES (32, 'South Africa');
INSERT INTO Country (CountryId, CountryName) VALUES (52, 'Mozambique');
INSERT INTO Country (CountryId, CountryName) VALUES (109, 'Honduras');
INSERT INTO Country (CountryId, CountryName) VALUES (247, 'AEROCESAR');
INSERT INTO Country (CountryId, CountryName) VALUES (77, 'Sudan');
INSERT INTO Country (CountryId, CountryName) VALUES (288, 'RENTAXEL');
INSERT INTO Country (CountryId, CountryName) VALUES (283, 'AEROVARADERO');
INSERT INTO Country (CountryId, CountryName) VALUES (131, 'New Caledonia');
INSERT INTO Country (CountryId, CountryName) VALUES (210, 'East Timor');
INSERT INTO Country (CountryId, CountryName) VALUES (285, 'AIRWAVE');
INSERT INTO Country (CountryId, CountryName) VALUES (266, 'S.A.');
INSERT INTO Country (CountryId, CountryName) VALUES (316, 'AEROSOL');
INSERT INTO Country (CountryId, CountryName) VALUES (201, 'Macau');
INSERT INTO Country (CountryId, CountryName) VALUES (38, 'Equatorial Guinea');
INSERT INTO Country (CountryId, CountryName) VALUES (144, 'Oman');
INSERT INTO Country (CountryId, CountryName) VALUES (102, 'Gibraltar');
INSERT INTO Country (CountryId, CountryName) VALUES (166, 'Suriname');
INSERT INTO Country (CountryId, CountryName) VALUES (140, 'West Bank');
INSERT INTO Country (CountryId, CountryName) VALUES (215, 'Korea');
INSERT INTO Country (CountryId, CountryName) VALUES (22, 'Isle of Man');
INSERT INTO Country (CountryId, CountryName) VALUES (108, 'Guatemala');
INSERT INTO Country (CountryId, CountryName) VALUES (272, 'ALL STAR');
INSERT INTO Country (CountryId, CountryName) VALUES (151, 'Marshall Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (106, 'Turks and Caicos Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (291, 'AZIMUT');
INSERT INTO Country (CountryId, CountryName) VALUES (62, 'Guinea-Bissau');
INSERT INTO Country (CountryId, CountryName) VALUES (47, 'Madagascar');
INSERT INTO Country (CountryId, CountryName) VALUES (155, 'Taiwan');
INSERT INTO Country (CountryId, CountryName) VALUES (265, 'AVIOQUINTANA');
INSERT INTO Country (CountryId, CountryName) VALUES (152, 'Midway Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (209, 'Brunei');
INSERT INTO Country (CountryId, CountryName) VALUES (165, 'Bolivia');
INSERT INTO Country (CountryId, CountryName) VALUES (242, 'Ivory Coast');
INSERT INTO Country (CountryId, CountryName) VALUES (14, 'Belgium');
INSERT INTO Country (CountryId, CountryName) VALUES (123, 'Tonga');
INSERT INTO Country (CountryId, CountryName) VALUES (124, 'Kiribati');
INSERT INTO Country (CountryId, CountryName) VALUES (93, 'Malta');
INSERT INTO Country (CountryId, CountryName) VALUES (236, 'South Georgia and the Islands');
INSERT INTO Country (CountryId, CountryName) VALUES (76, 'Rwanda');
INSERT INTO Country (CountryId, CountryName) VALUES (246, 'Canadian Territories');
INSERT INTO Country (CountryId, CountryName) VALUES (202, 'Nepal');
INSERT INTO Country (CountryId, CountryName) VALUES (3, 'Iceland');
INSERT INTO Country (CountryId, CountryName) VALUES (278, 'AVIANCA');
INSERT INTO Country (CountryId, CountryName) VALUES (217, 'Latvia');
INSERT INTO Country (CountryId, CountryName) VALUES (180, 'Saint Lucia');
INSERT INTO Country (CountryId, CountryName) VALUES (307, 'ODINN');
